# Dynamic Infrastructure - Home Assignment

The goal of this assignment is to evaluate basic scientific data manipulation and library research work. It would take 1-2 hours at most. This notebook contains all the information required for this exercise and the solution should be also written in this notebook.

### Part 1: Scientific computing in NumPy

Your code should be efficient and readable. It is suggested that you use NumPy, however alternatives (i.e. numba) are welcome.

In [1]:
import numpy as np
import pandas as pd
import re

np.random.seed(42)
X = np.random.randint(low=0, high=50, size=(30, 4))

In [2]:
X

array([[38, 28, 14, 42],
       [ 7, 20, 38, 18],
       [22, 10, 10, 23],
       [35, 39, 23,  2],
       [21,  1, 23, 43],
       [29, 37,  1, 20],
       [32, 11, 21, 43],
       [24, 48, 26, 41],
       [27, 15, 14, 46],
       [43,  2, 36,  6],
       [20,  8, 38, 17],
       [ 3, 24, 13, 49],
       [ 8, 25,  1, 19],
       [27, 46,  6, 43],
       [ 7, 46, 34, 13],
       [16, 35, 49, 39],
       [ 3,  1,  5, 41],
       [ 3, 28, 17, 25],
       [43, 33,  9, 35],
       [13, 30, 47, 14],
       [ 7, 13, 22, 39],
       [20, 15, 44, 17],
       [46, 23, 25, 24],
       [44, 40, 28, 14],
       [44,  0, 24,  6],
       [ 8, 23,  0, 43],
       [ 7, 23, 10, 16],
       [ 7, 34, 34, 32],
       [ 4, 41, 38, 40],
       [27,  6,  8,  7]])

1. Calculate the mean values of each column in X.

In [3]:
# Your code here

np.mean(X, axis=0)

array([21.16666667, 23.5       , 21.93333333, 27.23333333])

2. Calculate the max value of each row in X.

In [4]:
# Your code here

np.mean(X, axis=1)

array([30.5 , 20.75, 16.25, 24.75, 22.  , 21.75, 26.75, 34.75, 25.5 ,
       21.75, 20.75, 22.25, 13.25, 30.5 , 25.  , 34.75, 12.5 , 18.25,
       30.  , 26.  , 20.25, 24.  , 29.5 , 31.5 , 18.5 , 18.5 , 14.  ,
       26.75, 30.75, 12.  ])

3. Calculate the median value of all the values of X.

In [5]:
# Your code here

np.median(X)

23.0

4. Normalize X such that every column will have a mean of 0 and a variance of 1.

In [6]:
# Your code here

normed = (X - X.mean(axis=0)) / X.std(axis=0)

normed.mean(axis=0)
normed.std(axis=0)

array([1., 1., 1., 1.])

5. Given a 1D array Y, calculate the difference between each two elements of Y and save the results in a 2D array. This can be done in a single line using broadcasting.

In [7]:
Y = np.linspace(1, 10, 10)
# Your code here
Y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
Y.reshape(10,1) 

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [9]:
Y.reshape(10,1) - Y

array([[ 0., -1., -2., -3., -4., -5., -6., -7., -8., -9.],
       [ 1.,  0., -1., -2., -3., -4., -5., -6., -7., -8.],
       [ 2.,  1.,  0., -1., -2., -3., -4., -5., -6., -7.],
       [ 3.,  2.,  1.,  0., -1., -2., -3., -4., -5., -6.],
       [ 4.,  3.,  2.,  1.,  0., -1., -2., -3., -4., -5.],
       [ 5.,  4.,  3.,  2.,  1.,  0., -1., -2., -3., -4.],
       [ 6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2., -3.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1.],
       [ 9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.]])

6. Considering a 10x3 matrix, A. Create a new matrix, B, where all rows in B are rows in A apart from rows that have the same value. For example, [2,2,2] will not be copied to B, however [1,4,4] will be copied to B. Solve this for numerical values only. This can be solved in a single line without explicit loops.

In [10]:
# Your code here

A = np.random.randint(1,4,(10,3))
A

array([[2, 1, 3],
       [3, 2, 1],
       [3, 2, 3],
       [3, 1, 3],
       [1, 3, 2],
       [3, 1, 1],
       [2, 3, 3],
       [2, 3, 3],
       [1, 3, 3],
       [2, 2, 1]])

In [11]:
A[~np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)]

array([[2, 1, 3],
       [3, 2, 1],
       [3, 2, 3],
       [3, 1, 3],
       [1, 3, 2],
       [3, 1, 1],
       [2, 3, 3],
       [2, 3, 3],
       [1, 3, 3],
       [2, 2, 1]])

### Part 2: Using Pandas


In [12]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")

chipo.head(5)  # view the first 5 entries


order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

1. How many items were ordered in total?

In [13]:
# Your code here

chipo['quantity'].sum()

4972

2. What was the total revenue?

In [14]:
sum(chipo.item_price.str.replace('$','').astype(float) * chipo.quantity)

/var/folders/pt/18wbc3xd3mxfftgh8_8_mvjc0000gn/T/ipykernel_9944/2057406778.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  sum(chipo.item_price.str.replace('$','').astype(float) * chipo.quantity)


39237.020000000055

3. How many orders were made?

In [15]:
# Your code here

chipo['order_id'].nunique()

1834

4. Count how many unique rows the dataframe has (i.e. ignore all rows that are duplicates).

In [16]:
# Your code here

chipo['order_id'].nunique()

1834

In [17]:
df = pd.DataFrame(
    {
        "From_To": [
            "LoNDon_paris",
            "MAdrid_miLAN",
            "londON_StockhOlm",
            "Budapest_PaRis",
            "Brussels_londOn",
        ],
        "FlightNumber": [10045, np.nan, 10065, np.nan, 10085],
        "Airline": [
            "KLM(!)",
            "<Air France> (12)",
            "(British Airways. )",
            "12. Air France",
            '"Swiss Air"',
        ],
    }
)

df.head()

From_To  FlightNumber              Airline
0      LoNDon_paris       10045.0               KLM(!)
1      MAdrid_miLAN           NaN    <Air France> (12)
2  londON_StockhOlm       10065.0  (British Airways. )
3    Budapest_PaRis           NaN       12. Air France
4   Brussels_londOn       10085.0          "Swiss Air"

5. Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column

In [18]:
# Your code here


df.FlightNumber = df.FlightNumber.interpolate().astype(int)
df

From_To  FlightNumber              Airline
0      LoNDon_paris         10045               KLM(!)
1      MAdrid_miLAN         10055    <Air France> (12)
2  londON_StockhOlm         10065  (British Airways. )
3    Budapest_PaRis         10075       12. Air France
4   Brussels_londOn         10085          "Swiss Air"

6. The From_To column would be better as two separate columns. Split each string on the underscore delimiter `_` to give a new temporary DataFrame with the correct values. Assign the correct column names to this temporary DataFrame.

In [19]:
df2 = df.copy()
df2[["From", "To"]] = df.From_To.str.lower().str.split("_", expand=True)
df2 = df2[['FlightNumber', 'Airline', 'From', 'To']]
df2

FlightNumber              Airline      From         To
0         10045               KLM(!)    london      paris
1         10055    <Air France> (12)    madrid      milan
2         10065  (British Airways. )    london  stockholm
3         10075       12. Air France  budapest      paris
4         10085          "Swiss Air"  brussels     london

7. In the Airline column, you can see some extra punctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. '(British Airways. )' should become 'British Airways'.

In [20]:
# Your code here

df2['Airline'] = df2['Airline'].str.replace('[^a-zA-Z\s]', '')
df2

/var/folders/pt/18wbc3xd3mxfftgh8_8_mvjc0000gn/T/ipykernel_9944/3170242580.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df2['Airline'] = df2['Airline'].str.replace('[^a-zA-Z\s]', '')


FlightNumber           Airline      From         To
0         10045               KLM    london      paris
1         10055       Air France     madrid      milan
2         10065  British Airways     london  stockholm
3         10075        Air France  budapest      paris
4         10085         Swiss Air  brussels     london